$(document).ready(function (){
    var html = '<nav class="navbar navbar-expand-lg navbar-dark bg-gradient-primary fixed-top ">'
    html += '<div class="container">'
    html +=    '<a class="navbar-brand h1 mb-0" href="#">Washington Dealership</a>'
    html +=    '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">'
    html +=         '<span class="navbar-toggler-icon"></span>'
    html +=    '</button>'
    html +=    '<div class="collapse navbar-collapse" id="navbarResponsive">'
    html +=        '<ul class="navbar-nav mr-auto">'
    html +=            '<li class="nav-item" id="home-nav">'
    html +=                '<a class="nav-link" href="#">Home'
    html +=                '</a>'
    html +=            '</li>'
    html +=            '<li class="nav-item" id="about-nav">'
    html +=                '<a class="nav-link" href="#">About Us</a>'
    html +=            '</li>'
    html +=            '<li class="nav-item" id="services-nav">'
    html +=                '<a class="nav-link" href="#">Services</a>'
    html +=            '</li>'
    html +=            '<li class="nav-item" id="contact-nav">'
    html +=                '<a class="nav-link" href="#">Contact</a>'
    html +=            '</li>'
    html +=        '</ul>'
    html +=    '</div>'
    html += '</div>'
    html += '</nav>'
    $("#header-navbar").append(html)
})